[package]
name = "run-task"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.9"
tokio = { version = "^1", features = ["full"] }
chrono = { version = "0.4"}
serde = { version = "1.0", features = ["derive"] }
async-trait = "^0.1"